apiVersion: v2
name: yourss
type: application
version: 0.80.0
appVersion: 0.80.0
description: Simple Youtube browser based on RSS feeds
home: https://github.com/essembeh/YouRSS
icon: https://raw.githubusercontent.com/essembeh/YouRSS/main/src/yourss/static/icons/icon-192.png
keywords:
  - youtube
  - rss
maintainers:
  - email: essembeh@users.noreply.github.com
    name: Sébastien MB
sources:
  - https://github.com/essembeh/YouRSS
