@base_url = http://localhost:8000

@channel_id = UCVooVnzQxPSTXTMzSi1s6uw

###
GET {{base_url}}/u/alice
Authorization: Basic alice foo

###
GET {{base_url}}/u/alice
Authorization: Basic alice bar

### 
GET {{base_url}}/u/bob
Authorization: Basic bob foo

### 
GET {{base_url}}/u/bob
Authorization: Basic bob bar

### 
GET {{base_url}}/u/demo

###
GET {{base_url}}/api/rss/{{channel_id}}

###
GET {{base_url}}/api/avatar/{{channel_id}}