apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "yourss.fullname" . }}
  labels:
    {{- include "yourss.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "yourss.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "yourss.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "yourss.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.yourss.image.repository }}:{{ .Values.yourss.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.yourss.image.pullPolicy }}
          env:
            - name: TZ
              value: {{ .Values.yourss.timezone | quote }}
            - name: LOGURU_LEVEL
              value: {{ .Values.yourss.logLevel | quote }}
            - name: YOURSS_CUSTOM_PAGES_ENABLED
              value: {{ .Values.yourss.customPagesEnabled | quote }}
            - name: YOURSS_MAX_PAGE_ITEMS
              value: {{ .Values.yourss.maxPageItems | quote }}
            - name: YOURSS_API_DOCS_ENABLED
              value: {{ .Values.yourss.apiDocsEnabled | quote }}
            - name: YOURSS_CLEAN_TITLES
              value: {{ .Values.yourss.cleanTitles | quote }}
            - name: YOURSS_CHANNEL_CACHE_TTL
              value: {{ .Values.yourss.channelCacheTtl | quote }}
            {{- if .Values.yourss.cacheEnabled }}
            - name: YOURSS_CACHE_FOLDER
              value: /tmp/yourss-cache
            - name: YOURSS_CACHE_MAX_AGE
              value: {{ .Values.yourss.cacheMaxAge | quote }}
            {{- end }}
            {{- if .Values.yourss.users }}
            - name: YOURSS_USERS_FILE
              value: /yourss/users.yaml
            {{- end }}
            {{- with .Values.yourss.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/version
              port: http
          readinessProbe:
            httpGet:
              path: /api/version
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            {{- if .Values.yourss.users }}
            - name: users
              mountPath: /yourss
              readOnly: true
            {{- end }}
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
        {{- if .Values.yourss.users }}
        - name: users
          secret:
            secretName: {{ include "yourss.fullname" . }}-users
        {{- end }}
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
